version: "3"

vars:
  # Binaries
  LOCAL_BIN: "{{.TASKFILE_DIR}}/bin"
  # Source
  SOURCE_MAIN_FILE: "./cmd/gotchex/main.go"
  # Build
  BUILD_DIR: "./build"
  BUILD_BIN_FILE: "gotchex"

tasks:
  default:
    silent: true
    cmds:
      - task --list --color

  build:
    desc: "Build the application"
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.BUILD_BIN_FILE}} {{.SOURCE_MAIN_FILE}}

  test:
    desc: "Run tests"
    cmds:
      - go test ./... -v

  format:
    desc: "Format the code"
    cmds:
      - go fmt ./...

  lint:
    desc: "Lint the code"
    cmds:
      - "{{.LOCAL_BIN}}/golangci-lint run ./... --config .golangci.yml"

  tidy:
    desc: "Run go mod tidy"
    cmds:
      - go mod tidy

  install-dev-deps:
    desc: "Install dev binary dependencies"
    cmds:
      - mkdir -p {{.LOCAL_BIN}}
      - GOBIN={{.LOCAL_BIN}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6

  utils:size:
    desc: "Print the size of the binary"
    deps: [build]
    cmds:
      - du -h {{.BUILD_DIR}}/{{.BUILD_BIN_FILE}}
